### ISSUE TITLE
Issues with Ubuntu 24.04 Docker Images

### ISSUE THREAD

**Issue by tomcreutz** [dfki-ric/docker_image_development#101]
Hi,
recently I was setting up a ROS2 Jazzy Docker image with Ubuntu 24.04. Unfortunately it seems like there are some kind of breaking changes with this particular version. When creating the base image as usual and wanting to the set up the workspace, I get an permission error message:
mkdir: cannot create directory ‘/opt/workspace/src’: Permission denied

The same setup_workspace script was working just fine for ROS2 Humble and Ubuntu 22.04. Did you / anyone else have those problems and are there any fixes planned for that? I suspect that it might be connected to how permissions and users are handled? Apparently starting from 23.10, there is a default non-root user available in the ubuntu base image (https://bugs.launchpad.net/cloud-images/+bug/2005129).

**Comment by ndahn** [comment]
Encountered the same issue, didn't find a solution yet.

**Comment by ndahn** [comment]
Changing the dockeruser ID in `init_user_id.bash` to e.g. 1001 works, but I suspect that's not the solution you want to go with.

**Comment by planthaber** [comment]
Can you test: https://github.com/dfki-ric/docker_image_development/pull/102

That should fix the permission issue, i guess you'll also need to change the init_workspace to use Jazzy instead of Humble

**Comment by ndahn** [comment]
It works, but I'm not sure if running the docker container as `root` is the best solution... For now I'll stick to changing the dockeruser UID to 1001. The alternative would be to check if a user with UID 1000 already exists, and if so reuse that one instead of `dockeruser`, but that seems to involve many changes throughout the package.

**Comment by ndahn** [comment]
It works, thanks! I removed the "-u root" line in `docker_commands` though, don't think it's necessary.

**Comment by planthaber** [comment]
-u root was needed for me when creating a new container, let me check again

**Comment by ndahn** [comment]
Created a new base image and then a devel image for our workspace on top of it. Definitely not needed :)

**Comment by planthaber** [comment]
It is for me, nevertheless, not the scripts in the PR are setting the user explicitly  on each call, it is much clearer this way what is happening
