### ISSUE TITLE
[Feature Request] Suppress docker related output

### ISSUE THREAD

**Issue by 0Nel** [dfki-ric/docker_image_development#16]
I just had a use case in which I wanted the plain output of a command executed inside the container. Without all the docker and repo related output. I guess this use case could become more common and therefore I'd propose to add a -q or --quite option to the exec.bash script.

Adding more arguments to exec.bash would possibly enforce us to use proper argument handling, but I think we could keep this in mind for potential future rewrites?

**Comment by planthaber** [comment]
Here is a proposal: https://github.com/dfki-ric/docker_image_development/pull/17
