### ISSUE TITLE
WiP: Use of xpra for X server forwarding

### ISSUE THREAD

**Issue by planthaber** [dfki-ric/docker_image_development#45]
[XPRA](https://xpra.org/) is an remote display server and client tool that can be used as an alternative to mount x-server stuff in the exec.bash file: https://github.com/dfki-ric/docker_image_development/blob/bce9ba60dc69104616eecf2a0af52d56b452eca4/.docker_scripts/exec.bash#L116

Where sockets and the DISPLAY environment variable can change during the container lifetime.

A simple test (forward all desktop content) can be done like this:

In the container:
```bash 
sudo apt install xpra
export XDG_RUNTIME_DIR=~/.xpra
mkdir -p $XDG_RUNTIME_DIR/xpra
xpra start --bind-tcp=0.0.0.0:10000
``` 
look for "Actual display used: :1"
export DISPLAY=:1 in the docker to forward with xpra

connext from remote:
```bash 
sudo apt install xpra
xpra attach tcp:IP_WHERE_CONTAINER_RUNS:10000/
``` 

When --net=host is set in settings.bash, this can be used remotely

We could have an option in the settings.bash on what to use, and start the xpra server in the entrypont and also the client in the .exec.bash script automatically, if enabled.

The settigns.bash also needs to configure a port that is 
* exposed if net=host is not used (can we expose it anyway?)
* free (perhaps check which one is still free and auto-select for local applications?)
  * port info needs to be available to be able to conntect from remote

**Comment by planthaber** [comment]
One Question is how secure should it be:
 * just open port?
 * force ssh?
   *  auto setup ssh key login so no password is required?

**Comment by planthaber** [comment]
Addressed here:

https://github.com/dfki-ric/docker_image_development/pull/50

**Comment by 0Nel** [comment]
@planthaber this issue is resolved by the new xpra implementation right?

**Comment by planthaber** [comment]
yes
