### ISSUE TITLE
Run container with CUDA support?

### ISSUE THREAD

**Issue by moooeeeep** [dfki-ric/docker_image_development#47]
In the readme there is instructions for how to let your applications do rendering using the nvidia GPU: https://github.com/dfki-ric/docker_image_development/blob/master/doc/010_Setup_Docker.md#nvidia-docker-2

Right now I stumbled accross the problem that one of the things running inside the container require CUDA support from my GPU (e.g., tensorflow), which apparantly doesn't work yet, or at least requires extra steps. (Tensorflow complains about libcudart.so and lubcuda.so missing. My simulation appears in the nvidia-smi process list, but the Tensorflow processes just use the CPU instead.)

Do you have any experience with setting that up? 

I found [this documentation](https://www.celantur.com/blog/run-cuda-in-docker-on-linux/), is this how it works?

Do I need to integrate some special docker image into my image? Or build my own base image based on a `nvidia/cuda` image instead (normally [this is used](https://github.com/dfki-ric/docker_image_development/blob/master/image_setup/01_base_images/build_rock_master_20.04.bash#L9))?

Or do I need to install it inside the container as [described here](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation-network)?

**Comment by planthaber** [comment]
Hi,

This could be related to the base image used to create the images.

Currently we use https://hub.docker.com/r/nvidia/opengl base images. F
For CUDA, I guess you need to use images from https://hub.docker.com/r/nvidia/cudagl

To test, you can change it e.g. here: https://github.com/dfki-ric/docker_image_development/blob/master/image_setup/01_base_images/build_plain_20.04.bash#L9

And use the script to build a base image for CUDA, in case it works also with x11 (and acceleration) in development we could switch completely to use the cuda images.

**Comment by moooeeeep** [comment]
Maybe nvidia runtime wasn't installed or `--gpus all` wasn't passed for some reason. Anyways, this is obsolete to me now and therefore I'm closing this.
