### ISSUE TITLE
quickstart with ros noetic development

### ISSUE THREAD

**Issue by vanem** [dfki-ric/docker_image_development#51]
What I would like:
to build a ROS noetic base image locally and run it with GPU support

What I did:
- edit settings.bash:
export PROJECT_NAME=myprj
export WORKSPACE_BASE_IMAGE=developmentimage/ros_noetic_20.04:base

`./image_setup/01_base_images/build_ros_noetic_20.04.bash `
- now I have:
```
~/ros1/docker/docker_image_development$ docker image list
REPOSITORY                                  TAG                           IMAGE ID       CREATED         SIZE
developmentimage/ros_noetic_20.04           base                          d998a5e68375   2 hours ago     3.32GB
```
- then I try:
```
 ./exec.bash devel
overriding default execmode base to: devel

using developmentimage/docker_image_development:devel

Error: No such object: developmentimage/docker_image_development:devel
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
Unable to find image 'developmentimage/docker_image_development:devel' locally
devel: Pulling from developmentimage/docker_image_development
171857c49d0f: Downloading [================================================>  ]  25.89MB/26.7MB
419640447d26: Download complete
```
At this point I CTRL+C to interrupt de the download. Why is the script trying to pull the image of the internet? How can I use the  local base image for development (and then for release)?

**Comment by 0Nel** [comment]
Hi @vanem,

there are three types of images that we use: `base`, `devel` and `release`.

You are building the base image locally, but when generating a container with `exec.bash` you are passing the `devel` argument. Thus the `devel` image is used, which does not exist locally and is therefore pulled. If you have not changed the `DEFAULT_EXECMODE` in your `settings.bah` file than you can just remove the `devel`argument and work with your local base image.

**Comment by 0Nel** [comment]
For using the local base image as devel image, you have to build the devel image locally. You can simply execute `image_setup/02_devel_image/build.bash`. This image will be based on your noetic base image and you can use the Dockerfile to add project specific dependencies to that devel image.

After setting up your workspace it is highly recommended to execute: `./exec.bash devel write_osdeps` to parse your workspace dependencies and write them to the [workspace_os_dependencies.txt](https://github.com/dfki-ric/docker_image_development/blob/master/image_setup/02_devel_image/workspace_os_dependencies.txt) file. Afterwards you should rebuild your devel image to bake these dependencies into it.

This recommended workflow is described [here](https://github.com/dfki-ric/docker_image_development/blob/master/doc/042_Devel_Image.md#checklist-suggested-workflow)

**Comment by planthaber** [comment]
Also, this message tells me that when you tried to start the devel image, the project name was unchanged:

```
Unable to find image 'developmentimage/docker_image_development:devel' locally
devel: Pulling from developmentimage/docker_image_development
```
This is why it could download out existing example devel image ;-)

when the project name is changes, your devel image should have this name:

`developmentimage/myprj:devel`

**Comment by planthaber** [comment]
Closing due to no more activity
