### ISSUE TITLE
Why adding the os dependencies to the Dockerfile?

### ISSUE THREAD

**Issue by Rauldg** [dfki-ric/docker_image_development#9]
In the devel image documentation is stated that the os dependencies should be added to the [dockerfile](https://github.com/dfki-ric/docker_image_development/blob/master/doc/042_Devel_Image.md#installation-of-workspace-dependencies-in-the-dockerfile) and a script is provided to find out in your stack which are those.

Since autoproj update automatically installs those dependencies on its own, why adding them to the Dockerfile?

**Comment by Rauldg** [comment]
I just show the reason for that a few lines below `The later release image is not based on the devel container, it is based on the image. Any tools or dependencies not installed via the Dockerfile of the devel image will not be available in the release.`

The problem I identify here is that someone has to keep track that those dependencies are updated, or is there any automatic process for that?

**Comment by planthaber** [comment]
Basically these are the requirements:
1. There should be no issues when the container is deleted (when docker was cleaned up or the image was updated)
2. The release image should be complete without any extra dependencies when used.
3. The release image should be as small as possible

Adding the install to the Dockerfile of the devel image provides that they don't have to be re-installed every time the container is re-created. This might happen, when you clean up docker e.g. with `docker system prune`. When all dependencies are added to the image (Dockerfile), nothing has to be re-installed once you re-create the container after such a cleanup.

Also while in development, you might need extra tooling in your container that you install manually (git-gui, gdb, valgrind, etc.) that should not go into the release. We cannot differentiate between autoproj-installed pakages that should be in the release and user installed packages that should not. So we cannot just commit the container. Apart from the reason that not all images will have an OS dependency tool (autoproj/rosdep, etc.)

Keeping track in the development phase is not that hard with several options:
* Before creating a release use one of the list_*_osdeps scripts [here](https://github.com/dfki-ric/docker_image_development/tree/master/image_setup/02_devel_image) for a complete list of required packages of the workspace.
* When updating the devel workspace (autoproj, rosdep), watch for newly installed packages (possibly delete the container first to start with a fresh one). 
* Use a "test" release and do a osdep update in a release container and watch for newly installed packages.

**Comment by planthaber** [comment]
Added some more description: https://github.com/dfki-ric/docker_image_development/pull/10

**Comment by 0Nel** [comment]
Hi there,

thanks for your input @Rauldg!

```
The problem I identify here is that someone has to keep track that those dependencies are updated, or is there any automatic process for that?
```

In general I guess that most docker_development project should have an active maintainer, who should be aware of updating the Dockerfiles every now and then. I do agree that most temporary users will probably not be aware of this functionality.

Maybe we can find a neat way to automate this. One really accurate, but cumbersome way could be to add some routine to the docker_commands.bash that compares the output of the list_*_osdeps.bash scripts with the entries in the Dockerfile and print an info. Alternatively it might be a good middle ground to implement a similar routine that gets triggered, when building a new release image. For now, we could echo an instructive info from the 03_release_image/build.bash?

**Comment by Rauldg** [comment]
Thanks a lot for the clarifications!

> One really accurate, but cumbersome way could be to add some routine to the docker_commands.bash that compares the output of the list_*_osdeps.bash scripts with the entries in the Dockerfile and print an info.

Yes, that would make it. Updating directly the Dockerfile would be even nicer instead of printing the info seems even better. 

> For now, we could echo an instructive info from the 03_release_image/build.bash?

Actually I wasn't even planing to build a release image, just a devel one but indeed seems like producing a release with any missing dependency is worse than producing a devel image missing dependencies, since it is the user and not the developer team who will find out about the missing dependency.

**Comment by planthaber** [comment]
We could change the list_*_osdeps scritps to generate a install_workspace_dependencies.bash which we can save outside the container and in the Dockerfile.
To do this, we could mount the image_setup/02_devel_image/ folder into the devel image, as we do the the base container.

This would make maintaining the list easier as you only have to run the script. 
I'd also keep the "apt install" command in the Dockerfile when someone wants to install more default packages in the devel image, but afterwards call the install_workspace_dependencies.bash script to install them in the devel image.

Then, when building a release, we'd have to start the devel image and run the list_*_osdeps scritpt inside to auto-update the install script (should be directly possible by calling ./exec devel list_*_osdeps right?)

Then we can then just call the install script when building the release to make sure all deps are installed (as long they are correctly modelled int he workspace).

But one thing remains, we would need to find a way call the correct list_*_osdeps script for the workspace and the correct workspace folder.

I'd say we could start with changing the list osdeps scripts to create install scritps to be used and updated from for the devel image. And print a warning in the release build script to update the install_workspace_dependencies.bash script from the devel container (using the script in case there is one for the workspace).

What do you think?

**Comment by Rauldg** [comment]
>But one thing remains, we would need to find a way call the correct list_*_osdeps script for the workspace and the correct workspace folder.

Yes, actually I was wondering sometimes (while creating the devel image) if I should add this repo, more specifically the fork for my project, into my project's manifest. By doing that, and running the script from within the project the workspace would be directly found, right?

> What do you think?

Looks good as far as I can tell.
