### ISSUE TITLE
Only apt dependencies are tracked and installed in the Dockerfile for the devel image

### ISSUE THREAD

**Issue by moooeeeep** [dfki-ric/docker_image_development#97]
Autoproj, as well as rosdep, can install pip dependencies. These are however not installed in the Dockerfile and will thus be found missing subsequently.

---

The [script for listing deps from rosdep ](https://github.com/dfki-ric/docker_image_development/blob/master/image_setup/02_devel_image/list_ros_osdeps.bash) does not correctly parse reported pip dependencies.

Potential output:
```
$ rosdep install --from-paths /opt/workspace/src --ignore-src --simulate --reinstall -r 
#[apt] Installation commands:
  sudo -H apt-get install python3-pytest
#[pip] Installation commands:
  sudo -H pip3 install -U -I canopen
```

Turns to 

```
python3-pytest 

-I 
```

**Comment by planthaber** [comment]
Can you test: https://github.com/dfki-ric/docker_image_development/pull/98 this should fix the apt dependencies.

Python-pip deps should normally be installed in the users home directory or workspace, (mounted folders, copied into release image), so no need to install them in the devel image directly to have a working release. If you want to save time, you can add them manually in your 02_devel_image/Dockerfile
